INSERT INTO todo (task, status, category, importance, comp) VALUES

('Make To-Do app for class (Meta!)',
'Do',
'Coding',
8,
'False'),
('Revise résumé for outcomes',
'Do',
'Job Search',
6,
'False'),
('Revise LinkedIn for outcomes',
'Delay',
'Job Search',
4,
'False'),
('Watch Pickle and Peanut with Zephyr',
'Do',
'Parenting',
9,
'False'),
('Fix back to deck bug in Zimi',
'Delay',
'Coding',
6,
'False')
